name: Delete artifacts

on:
  workflow_call:
    inputs:
      pr:
        default: false
        description: "Remove artifacts only on PR mode"
        required: false
        type: boolean

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Delete artifacts from previous runs
        if: ${{ !inputs.pr || inputs.pr && github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          script: |
            const runsResponse = await github.request("GET /repos/${{ github.repository }}/actions/runs")
            for (workflow_run of runsResponse.data.workflow_runs) {
              if (workflow_run.name == "${{ github.workflow }}" && workflow_run.status !== "in_progress") {
                if (workflow_run.id == "${{ github.run_id }}") {
                  console.log(`Ignoring delete self-run ${workflow_run.id}`)
                  continue
                }
                console.log(`Deleting artifacts from workflow run ${workflow_run.id}`)
                const response = await github.request(`GET /repos/${{ github.repository }}/actions/runs/${workflow_run.id}/artifacts`)
                for (artifact of response.data.artifacts) {
                  console.log(`\tDeleting artifact with id ${artifact.id}`)
                  const deleteResponse = await github.request(`DELETE /repos/${{ github.repository }}/actions/artifacts/${artifact.id}`)
                }
              }
            }