name: PHP Static Analysis

on:
  workflow_call:
    inputs:
      configuration:
        description: "Path of the configuration file"
        required: false
        type: string
      composer:
        description: "Path of composer.json file within root project folder"
        required: true
        type: string
      memory:
        default: "256M"
        description: "Memory limit"
        required: false
        type: string
      path:
        description: "Which path of the project to scan for"
        required: true
        type: string

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure composer
        uses: php-actions/composer@v6
        with:
          working_dir: ${{ inputs.composer }}

      - name: Run phpstan
        uses: php-actions/phpstan@v3
        with:
          configuration: ${{ inputs.configuration }}
          memory_limit: ${{ inputs.memory }}
          path: ${{ inputs.path }}