name: PHP Static Analysis

on:
  workflow_call:
    inputs:
      configuration:
        description: "Path of the configuration file"
        required: false
        type: string
      composer:
        description: "Path of composer.json file within root project folder"
        required: true
        type: string
      memory:
        default: "512M"
        description: "Memory limit"
        required: false
        type: string
      path:
        description: "Which path of the project to scan for"
        required: true
        type: string

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Filter changed files on path
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            path:
              - '${{ inputs.path }}**'


      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: '8.3'

      - name: Configure composer
        if: ${{ steps.filter.outputs.path == 'true' }}
        uses: php-actions/composer@v6
        with:
          version: 2.8.1
          working_dir: ${{ inputs.composer }}

      - name: Run phpstan
        if: ${{ steps.filter.outputs.path == 'true' }}
        uses: php-actions/phpstan@v3
        with:
          configuration: ${{ inputs.configuration }}
          memory_limit: ${{ inputs.memory }}
          path: ${{ inputs.path }}
          version: latest