name: Semgrep

on:
  workflow_call:

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check token
        env:
          token: ${{ secrets.SEMGREP_APP_TOKEN }}
        if: ${{ env.token == '' }}
        run: exit 1

      - name: Semgrep CI
        run: semgrep ci --sarif --output=semgrep.sarif
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
        if: always()