name: Semgrep

on:
  workflow_call:
    inputs:
      security-dashboard:
        default: false
        description: "Upload to Security tab (requires Advanced Security)"
        required: false
        type: boolean
      semgrep-options:
        default: ""
        description: "Options passed to semgrep CLI"
        required: false
        type: string
    secrets:
      SEMGREP_APP_TOKEN:
        required: true

jobs:
  analyze:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Semgrep CI (Upload to Semgrep UI)
        if: ${{ !inputs.security-dashboard }}
        shell: bash
        run: |
          # Run CLI
          echo "See semgrep results in https://semgrep.dev/orgs/-"
          semgrep ci --verbose --no-suppress-errors ${{ inputs.semgrep-options }}
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      - name: Semgrep CI (Upload to Advanced Security Dashboard)
        if: ${{ inputs.security-dashboard }}
        shell: bash
        run: semgrep ci --verbose --sarif --output=semgrep.sarif ${{ inputs.semgrep-options }}
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        if: ${{ inputs.security-dashboard }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif