name: Test LaTeX

on:
  workflow_call:
    inputs:
      checkout-fetch-depth:
        default: 1
        description: "Number of commits to fetch. 0 indicates all history for all branches and tags"
        required: false
        type: number
      file:
        description: "Name of the tex file to test (without extension)"
        required: true
        type: string
      timeout:
        default: 120
        description: "Job timeout"
        required: false
        type: number
      upload-gdrive:
        default: false
        description: "Upload to google drive. Requires secrets GDRIVE_FOLDERID and GDRIVE_CREDENTIALS"
        required: false
        type: boolean
      upload-gdrive-name:
        default: ""
        description: "Name of the new file, without extension. If no defined, use the same of the compiled latex"
        required: false
        type: string
      upload-gdrive-overwrite:
        default: true
        description: "Overwrites the file if already exists with the same name"
        required: false
        type: boolean
      upload-github:
        default: true
        description: "Upload compiled PDF to github actions artifact"
        required: false
        type: boolean
    secrets:
      ACTIONS:
        required: false
      GDRIVE_CREDENTIALS:
        required: false
      GDRIVE_FOLDERID:
        required: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout }}
    steps:
      - name: Checkout
        env:
          token: ${{ secrets.ACTIONS }}
        if: ${{ env.token == '' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ inputs.checkout-fetch-depth }}
          submodules: recursive

      - name: Checkout (with token)
        env:
          token: ${{ secrets.ACTIONS }}
        if: ${{ env.token != '' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ inputs.checkout-fetch-depth }}
          submodules: recursive
          token: ${{ secrets.ACTIONS }}

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: ${{ inputs.file }}.tex

      - name: Check pdf files
        run: |
          ls -l
          file ${{ inputs.file }}.pdf | grep -q ' PDF '

      - name: Upload PDF (Github)
        if: ${{ inputs.upload-github }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.file }}
          path: ${{ inputs.file }}.pdf

      - name: Upload PDF (Google Drive)
        if: ${{ inputs.upload-gdrive && inputs.upload-gdrive-name == '' }}
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          filename: ${{ inputs.file }}.pdf
          folderId: ${{ secrets.GDRIVE_FOLDERID }}
          name: ${{ inputs.file }}.pdf
          overwrite: ${{ inputs.upload-gdrive-overwrite }}

      - name: Upload PDF (Google Drive with custom name)
        if: ${{ inputs.upload-gdrive && inputs.upload-gdrive-name != '' }}
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          filename: ${{ inputs.file }}.pdf
          folderId: ${{ secrets.GDRIVE_FOLDERID }}
          name: ${{ inputs.upload-gdrive-name }}.pdf
          overwrite: ${{ inputs.upload-gdrive-overwrite }}